### ISSUE TITLE
Some odds and ends

### ISSUE THREAD

**Issue by zeusome** [c0gent/NeverClicker#11]
**Feature Suggestion** When a toon fills the XP bar it creates a box "Collect Overflow Reward" that needs to be clicked. There should be an option on NClick whether to collect these overflow rewards automatically or not. 

**Feature Suggestion** Multiple accounts. Could this implement an option that allows multiple accounts? My current invoker for example asked the number of accounts upfront, Configured them all with the username/pw and number of toons for each acct, and saved that info. It runs through all the accounts in linear sequence (goes to login screen, enters UN/PW) with each loop. 

**Feature Suggestion** Would prefer to collect Enchanted coffers rather than Artifact paraphenalia since rank5s are more profitable now. Some basic options as to which profession tasks to run would be great. 

**Issue:** For some reason, I had an issue where Neverclicker went out of Neverwinter Window and the mouse cursor was moving around/clicking things on my desktop. I returned to PC and several desktop apps had been opened. Will monitor this problem and provide more info when available. 

**Issue.** Neverclicker did not fill out some of my toons professions completely. Instead of 3x Resobag, 3x Thaumbag, and 3x ArtiParaphenlia task, it filled in 3x Resobag, 3x ArtiParaphenalia task and left 2 slots blank and went to next toon. I don't know why but this happened with a number of toons. 

**Feature Suggestion:** NClicker Start Delay: The autoinvoker I was using had a box like "Start delay ____ minutes". This was nice.. could leave the Nwinter window on Char select screen, leave the bot open, then it would start run automatically after specified time, such as in the early morning after server reset. There was even a feature on start up which asked "Get minutes until server reset?"..Click Yes and it would connect with NIST and calculate the minutes to server reset (6am for me) and fill this time in the start delay box.

**Comment by c0gent** [comment]
Great feedback. Just a few thoughts and counter-arguments to give you my train of thought. Don't take this as criticism and please do fire back at me if my reasoning is unsound.

**Feature Suggestion** "Collect Overflow Reward":  I'm hesitant to add this for a few reasons. It's something easily done manually. The rewards don't take up inventory space and can sit there indefinitely. If you do collect the rewards, they can take up extra inventory space (which can be problematic). I'd have to be convinced before wanting to add this. 

**Feature Suggestion** Multiple accounts:  Great idea, there is a framework for this already in the program but would take some doing before it would be usable. I'll put this on the long-term list for sure. **[Tracking Issue](https://github.com/c0gent/NeverClicker/issues/13)**

**Feature Suggestion** Custom profession tasks:  Definitely already on the list. **[Tracking Issue](https://github.com/c0gent/NeverClicker/issues/14)**

**Issue** Cursor:  That's something I definitely need to fix. See if you can figure out what conditions are causing it so that I can try to reproduce it. I'll consider this a high priority item. **[Tracking Issue](https://github.com/c0gent/NeverClicker/issues/12)**

**Issue** Profession tasks:  I've seen this happen as well, the profession logic is a bit janky and has certain limitations. Part of the problem is probably that the screen took too long after finishing adding a new task to refresh to a point where NeverClicker could detect the empty slot visually. I'll add some extra delay by default or add an option for extra delay at this spot and we'll see if that takes care of it. **[Tracking Issue](https://github.com/c0gent/NeverClicker/issues/15)**

**Feature Suggestion** NClicker Start Delay: This is already how NeverClicker works automatically. There is no option for it, it calculates the necessary delays and detects various conditions such as the server being down without any effort at all. Just leave NeverClicker running always (unless you're playing or using the computer), it will open the client at the correct times whenever it needs to.

**Comment by c0gent** [comment]
I'll add, by the way, that the profession queue is still not working as intended. The system has quite a few cobwebs after sitting dormant for so long. For one thing, the tasks are not being re-added to the queue upon startup. This is my top priority right now and I should have some time to work on it later today.

**Comment by zeusome** [comment]
Nice work! I will check to see if overflow XP reward stack. If they do.. there is no need to auto-open them. 

One simple thing.. Is there an easy hotkey for cleanly pausing/unpausing NClicker? When its doing things in the game screen, I am having to fight it for the mouse to pull up the NClicker box and press stop.

**Comment by c0gent** [comment]
> I will check to see if overflow XP reward stack. If they do.. there is no need to auto-open them.

They do stack. I have probably 5 - 10 stacked up on my toons.

> Is there an easy hotkey for cleanly pausing/unpausing NClicker?

Unfortunately not. NeverClicker does not capture keyboard events, it only sends them. I messed with this a year or year and a half ago but never really came to a conclusion on how best to do this. It's definitely on the long term list. For now you just have to fight with it. Waiting until it logs on or logs off a character is generally the easiest time but yeah this needs some work.

**Comment by c0gent** [comment]
Keep these excellent suggestions coming.
