### ISSUE TITLE
Minor fix: Key collect errors

### ISSUE THREAD

**Issue by zeusome** [c0gent/NeverClicker#18]
NClick tries to collect the key with every toon: https://i.imgur.com/3LUPw6E.png
This generates a long list of error messages which kind of bury any genuine errors, and not efficient since its trying to collect key for every toon. 

Also NClicker starts at character 0.
Should be character 1 to avoid confusion I suppose.

**Comment by c0gent** [comment]
> NClick tries to collect the key with every toon

Yeah I think it does this if you collect it manually. I'll add an additional check for that situation.

> Also NClicker starts at character 0

Computer scientists and mathematicians count from zero, [as nature intended](https://www.cs.utexas.edu/users/EWD/transcriptions/EWD08xx/EWD831.html). I'll probably add an option for character names though, so that you can add names for each character and have that printed instead.

**Comment by zeusome** [comment]
Starting at 0 makes an unnecessary point of confusion in reading the NClick log activity/errors ie. if there is a problem with "Character 3" then most users will logically look at the third toon down in their in game menu (it would be the 4th toon).

**Comment by c0gent** [comment]
Fixed: 36a4335083a09ae22c92ad93bfe5fe52e44837c0
